
var Module = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(Module) {
  Module = Module || {};


var h;h||(h=typeof Module !== 'undefined' ? Module : {});var aa,ba;h.ready=new Promise(function(a,b){aa=a;ba=b});var ca=Object.assign({},h),da="./this.program",ea="object"==typeof window,fa="function"==typeof importScripts,ha="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,m="",ia,ja,ka,fs,la,ma;
if(ha)m=fa?require("path").dirname(m)+"/":__dirname+"/",ma=()=>{la||(fs=require("fs"),la=require("path"))},ia=function(a,b){ma();a=la.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")},ka=a=>{a=ia(a,!0);a.buffer||(a=new Uint8Array(a));return a},ja=(a,b,c)=>{ma();a=la.normalize(a);fs.readFile(a,function(d,e){d?c(d):b(e.buffer)})},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),process.on("uncaughtException",function(a){throw a;}),process.on("unhandledRejection",
function(a){throw a;}),h.inspect=function(){return"[Emscripten Module object]"};else if(ea||fa)fa?m=self.location.href:"undefined"!=typeof document&&document.currentScript&&(m=document.currentScript.src),_scriptDir&&(m=_scriptDir),0!==m.indexOf("blob:")?m=m.substr(0,m.replace(/[?#].*/,"").lastIndexOf("/")+1):m="",ia=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},fa&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
ja=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var na=h.print||console.log.bind(console),t=h.printErr||console.warn.bind(console);Object.assign(h,ca);ca=null;h.thisProgram&&(da=h.thisProgram);var oa;h.wasmBinary&&(oa=h.wasmBinary);var noExitRuntime=h.noExitRuntime||!0;"object"!=typeof WebAssembly&&w("no native wasm support detected");
var pa,qa=!1,ra="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function x(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ra)return ra.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
function sa(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var l=a.charCodeAt(++f);k=65536+((k&1023)<<10)|l&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function ta(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var ua="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function va(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&wa[c];)++c;c<<=1;if(32<c-a&&ua)return ua.decode(A.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=B[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}
function xa(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)B[b>>1]=a.charCodeAt(e),b+=2;B[b>>1]=0;return b-d}function ya(a){return 2*a.length}function za(a,b){for(var c=0,d="";!(c>=b/4);){var e=C[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function Aa(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var k=a.charCodeAt(++e);f=65536+((f&1023)<<10)|k&1023}C[b>>2]=f;b+=4;if(b+4>c)break}C[b>>2]=0;return b-d}function Ba(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var Ca,D,A,B,wa,C,E,Da,Ea,Fa,Ga=[],Ha=[],Ia=[];function Ja(){var a=h.preRun.shift();Ga.unshift(a)}var F=0,Ka=null,La=null;
h.preloadedImages={};h.preloadedAudios={};function w(a){if(h.onAbort)h.onAbort(a);a="Aborted("+a+")";t(a);qa=!0;a=new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Ma(){return G.startsWith("data:application/octet-stream;base64,")}var G;G="chess-wasm.wasm";if(!Ma()){var Na=G;G=h.locateFile?h.locateFile(Na,m):m+Na}
function Oa(){var a=G;try{if(a==G&&oa)return new Uint8Array(oa);if(ka)return ka(a);throw"both async and sync fetching of the wasm failed";}catch(b){w(b)}}
function Pa(){if(!oa&&(ea||fa)){if("function"==typeof fetch&&!G.startsWith("file://"))return fetch(G,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+G+"'";return a.arrayBuffer()}).catch(function(){return Oa()});if(ja)return new Promise(function(a,b){ja(G,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Oa()})}var H,Qa;
function Ra(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(h);else{var c=b.Cb;"number"==typeof c?void 0===b.Ca?Sa(c)():Sa(c)(b.Ca):c(void 0===b.Ca?null:b.Ca)}}}var Ta=[];function Sa(a){var b=Ta[a];b||(a>=Ta.length&&(Ta.length=a+1),Ta[a]=b=Fa.get(a));return b}
function Ua(a){this.V=a-16;this.$a=function(b){C[this.V+4>>2]=b};this.Xa=function(b){C[this.V+8>>2]=b};this.Ya=function(){C[this.V>>2]=0};this.Wa=function(){D[this.V+12>>0]=0};this.Za=function(){D[this.V+13>>0]=0};this.Va=function(b,c){this.$a(b);this.Xa(c);this.Ya();this.Wa();this.Za()}}var Va=0,Wa={};function Xa(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Ya(a){return this.fromWireType(E[a>>2])}var I={},J={},Za={};
function $a(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function ab(a,b){a=$a(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function bb(a){var b=Error,c=ab(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var cb=void 0;function db(a){throw new cb(a);}
function K(a,b,c){function d(l){l=c(l);l.length!==a.length&&db("Mismatched type converter count");for(var n=0;n<a.length;++n)L(a[n],l[n])}a.forEach(function(l){Za[l]=b});var e=Array(b.length),f=[],k=0;b.forEach(function(l,n){J.hasOwnProperty(l)?e[n]=J[l]:(f.push(l),I.hasOwnProperty(l)||(I[l]=[]),I[l].push(function(){e[n]=J[l];++k;k===f.length&&d(e)}))});0===f.length&&d(e)}
function eb(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var fb=void 0;function N(a){for(var b="";A[a];)b+=fb[A[a++]];return b}var O=void 0;function Q(a){throw new O(a);}
function L(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||Q('type "'+d+'" must have a positive integer typeid pointer');if(J.hasOwnProperty(a)){if(c.kb)return;Q("Cannot register type '"+d+"' twice")}J[a]=b;delete Za[a];I.hasOwnProperty(a)&&(b=I[a],delete I[a],b.forEach(function(e){e()}))}function gb(a){Q(a.R.Y.W.name+" instance already deleted")}var hb=!1;function ib(){}
function jb(a){--a.count.value;0===a.count.value&&(a.Z?a.aa.ia(a.Z):a.Y.W.ia(a.V))}function kb(a,b,c){if(b===c)return a;if(void 0===c.ba)return null;a=kb(a,b,c.ba);return null===a?null:c.cb(a)}var lb={},mb=[];function nb(){for(;mb.length;){var a=mb.pop();a.R.ma=!1;a["delete"]()}}var ob=void 0,pb={};function qb(a,b){for(void 0===b&&Q("ptr should not be undefined");a.ba;)b=a.sa(b),a=a.ba;return pb[b]}
function rb(a,b){b.Y&&b.V||db("makeClassHandle requires ptr and ptrType");!!b.aa!==!!b.Z&&db("Both smartPtrType and smartPtr must be specified");b.count={value:1};return sb(Object.create(a,{R:{value:b}}))}function sb(a){if("undefined"===typeof FinalizationRegistry)return sb=b=>b,a;hb=new FinalizationRegistry(b=>{jb(b.R)});sb=b=>{var c=b.R;c.Z&&hb.register(b,{R:c},b);return b};ib=b=>{hb.unregister(b)};return sb(a)}function R(){}
function tb(a,b,c){if(void 0===a[b].fa){var d=a[b];a[b]=function(){a[b].fa.hasOwnProperty(arguments.length)||Q("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].fa+")!");return a[b].fa[arguments.length].apply(this,arguments)};a[b].fa=[];a[b].fa[d.ta]=d}}
function ub(a,b){h.hasOwnProperty(a)?(Q("Cannot register public name '"+a+"' twice"),tb(h,a,a),h.hasOwnProperty(void 0)&&Q("Cannot register multiple overloads of a function with the same number of arguments (undefined)!"),h[a].fa[void 0]=b):h[a]=b}function vb(a,b,c,d,e,f,k,l){this.name=a;this.constructor=b;this.na=c;this.ia=d;this.ba=e;this.fb=f;this.sa=k;this.cb=l;this.ob=[]}
function wb(a,b,c){for(;b!==c;)b.sa||Q("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.sa(a),b=b.ba;return a}function xb(a,b){if(null===b)return this.Ea&&Q("null is not a valid "+this.name),0;b.R||Q('Cannot pass "'+yb(b)+'" as a '+this.name);b.R.V||Q("Cannot pass deleted object as a pointer of type "+this.name);return wb(b.R.V,b.R.Y.W,this.W)}
function zb(a,b){if(null===b){this.Ea&&Q("null is not a valid "+this.name);if(this.wa){var c=this.Ga();null!==a&&a.push(this.ia,c);return c}return 0}b.R||Q('Cannot pass "'+yb(b)+'" as a '+this.name);b.R.V||Q("Cannot pass deleted object as a pointer of type "+this.name);!this.va&&b.R.Y.va&&Q("Cannot convert argument of type "+(b.R.aa?b.R.aa.name:b.R.Y.name)+" to parameter type "+this.name);c=wb(b.R.V,b.R.Y.W,this.W);if(this.wa)switch(void 0===b.R.Z&&Q("Passing raw pointer to smart pointer is illegal"),
this.vb){case 0:b.R.aa===this?c=b.R.Z:Q("Cannot convert argument of type "+(b.R.aa?b.R.aa.name:b.R.Y.name)+" to parameter type "+this.name);break;case 1:c=b.R.Z;break;case 2:if(b.R.aa===this)c=b.R.Z;else{var d=b.clone();c=this.pb(c,Ab(function(){d["delete"]()}));null!==a&&a.push(this.ia,c)}break;default:Q("Unsupporting sharing policy")}return c}
function Bb(a,b){if(null===b)return this.Ea&&Q("null is not a valid "+this.name),0;b.R||Q('Cannot pass "'+yb(b)+'" as a '+this.name);b.R.V||Q("Cannot pass deleted object as a pointer of type "+this.name);b.R.Y.va&&Q("Cannot convert argument of type "+b.R.Y.name+" to parameter type "+this.name);return wb(b.R.V,b.R.Y.W,this.W)}
function S(a,b,c,d){this.name=a;this.W=b;this.Ea=c;this.va=d;this.wa=!1;this.ia=this.pb=this.Ga=this.Ua=this.vb=this.nb=void 0;void 0!==b.ba?this.toWireType=zb:(this.toWireType=d?xb:Bb,this.da=null)}function Cb(a,b){h.hasOwnProperty(a)||db("Replacing nonexistant public symbol");h[a]=b;h[a].ta=void 0}
function Db(a,b){var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=h["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=Sa(b).apply(null,c);return d}}function T(a,b){a=N(a);var c=a.includes("j")?Db(a,b):Sa(b);"function"!=typeof c&&Q("unknown function pointer with signature "+a+": "+b);return c}var Eb=void 0;function Fb(a){a=Gb(a);var b=N(a);U(a);return b}
function Hb(a,b){function c(f){e[f]||J[f]||(Za[f]?Za[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Eb(a+": "+d.map(Fb).join([", "]));}function Ib(a,b){for(var c=[],d=0;d<a;d++)c.push(C[(b>>2)+d]);return c}
function Jb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=ab(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Kb(a,b,c,d,e){var f=b.length;2>f&&Q("argTypes array size mismatch! Must at least get return value and 'this' types!");var k=null!==b[1]&&null!==c,l=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].da){l=!0;break}var n="void"!==b[0].name,p="",q="";for(c=0;c<f-2;++c)p+=(0!==c?", ":"")+"arg"+c,q+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+$a(a)+"("+p+") {\nif (arguments.length !== "+(f-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(f-2)+" args!');\n}\n";l&&(a+="var destructors = [];\n");var u=l?"destructors":"null";p="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[Q,d,e,Xa,b[0],b[1]];k&&(a+="var thisWired = classParam.toWireType("+u+", this);\n");for(c=0;c<f-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+u+", arg"+c+"); // "+b[c+2].name+"\n",p.push("argType"+c),d.push(b[c+2]);k&&(q="thisWired"+(0<q.length?", ":"")+q);a+=(n?"var rv = ":"")+"invoker(fn"+(0<q.length?", ":"")+q+");\n";if(l)a+=
"runDestructors(destructors);\n";else for(c=k?1:2;c<b.length;++c)f=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].da&&(a+=f+"_dtor("+f+"); // "+b[c].name+"\n",p.push(f+"_dtor"),d.push(b[c].da));n&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");p.push(a+"}\n");return Jb(p).apply(null,d)}var Lb=[],V=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Mb(a){4<a&&0===--V[a].Ia&&(V[a]=void 0,Lb.push(a))}
function Ab(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Lb.length?Lb.pop():V.length;V[b]={Ia:1,value:a};return b}}function yb(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function Nb(a,b){switch(b){case 2:return function(c){return this.fromWireType(Da[c>>2])};case 3:return function(c){return this.fromWireType(Ea[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Ob(a,b,c){switch(b){case 0:return c?function(d){return D[d]}:function(d){return A[d]};case 1:return c?function(d){return B[d>>1]}:function(d){return wa[d>>1]};case 2:return c?function(d){return C[d>>2]}:function(d){return E[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var Pb={};
function Qb(){if(!Rb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Pb)void 0===Pb[b]?delete a[b]:a[b]=Pb[b];var c=[];for(b in a)c.push(b+"="+a[b]);Rb=c}return Rb}var Rb;
function Sb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function Tb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Sb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Ub(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Vb(a){if("/"===a)return"/";a=Tb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function Wb(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ha)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){w("randomDevice")}}
function Xb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Sb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var Yb=[];function Zb(a,b){Yb[a]={input:[],output:[],oa:b};$b(a,ac)}
var ac={open:function(a){var b=Yb[a.node.rdev];if(!b)throw new W(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.oa.flush(a.tty)},flush:function(a){a.tty.oa.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.oa.Qa)throw new W(60);for(var e=0,f=0;f<d;f++){try{var k=a.tty.oa.Qa(a.tty)}catch(l){throw new W(29);}if(void 0===k&&0===e)throw new W(6);if(null===k||void 0===k)break;e++;b[c+f]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.oa.Fa)throw new W(60);
try{for(var e=0;e<d;e++)a.tty.oa.Fa(a.tty,b[c+e])}catch(f){throw new W(29);}d&&(a.node.timestamp=Date.now());return e}},cc={Qa:function(a){if(!a.input.length){var b=null;if(ha){var c=Buffer.alloc(256),d=0;try{d=fs.readSync(process.stdin.fd,c,0,256,-1)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=
readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=bc(b,!0)}return a.input.shift()},Fa:function(a,b){null===b||10===b?(na(x(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(na(x(a.output,0)),a.output=[])}},dc={Fa:function(a,b){null===b||10===b?(t(x(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(t(x(a.output,0)),a.output=[])}},X={ea:null,ha:function(){return X.createNode(null,"/",16895,0)},createNode:function(a,
b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new W(63);X.ea||(X.ea={dir:{node:{ja:X.T.ja,ga:X.T.ga,lookup:X.T.lookup,xa:X.T.xa,rename:X.T.rename,unlink:X.T.unlink,rmdir:X.T.rmdir,readdir:X.T.readdir,symlink:X.T.symlink},stream:{la:X.U.la}},file:{node:{ja:X.T.ja,ga:X.T.ga},stream:{la:X.U.la,read:X.U.read,write:X.U.write,Ja:X.U.Ja,Ra:X.U.Ra,Ta:X.U.Ta}},link:{node:{ja:X.T.ja,ga:X.T.ga,readlink:X.T.readlink},stream:{}},Ka:{node:{ja:X.T.ja,ga:X.T.ga},stream:ec}});c=fc(a,b,c,d);16384===(c.mode&61440)?
(c.T=X.ea.dir.node,c.U=X.ea.dir.stream,c.S={}):32768===(c.mode&61440)?(c.T=X.ea.file.node,c.U=X.ea.file.stream,c.X=0,c.S=null):40960===(c.mode&61440)?(c.T=X.ea.link.node,c.U=X.ea.link.stream):8192===(c.mode&61440)&&(c.T=X.ea.Ka.node,c.U=X.ea.Ka.stream);c.timestamp=Date.now();a&&(a.S[b]=c,a.timestamp=c.timestamp);return c},Db:function(a){return a.S?a.S.subarray?a.S.subarray(0,a.X):new Uint8Array(a.S):new Uint8Array(0)},Ma:function(a,b){var c=a.S?a.S.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>
0),0!=c&&(b=Math.max(b,256)),c=a.S,a.S=new Uint8Array(b),0<a.X&&a.S.set(c.subarray(0,a.X),0))},qb:function(a,b){if(a.X!=b)if(0==b)a.S=null,a.X=0;else{var c=a.S;a.S=new Uint8Array(b);c&&a.S.set(c.subarray(0,Math.min(b,a.X)));a.X=b}},T:{ja:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.X:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);
b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.ab=4096;b.blocks=Math.ceil(b.size/b.ab);return b},ga:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&X.qb(a,b.size)},lookup:function(){throw gc[44];},xa:function(a,b,c,d){return X.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=hc(b,c)}catch(f){}if(d)for(var e in d.S)throw new W(55);}delete a.parent.S[a.name];a.parent.timestamp=Date.now();a.name=
c;b.S[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.S[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=hc(a,b),d;for(d in c.S)throw new W(55);delete a.S[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.S)a.S.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=X.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new W(28);return a.link}},U:{read:function(a,b,c,d,e){var f=a.node.S;
if(e>=a.node.X)return 0;a=Math.min(a.node.X-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.S||a.S.subarray)){if(f)return a.S=b.subarray(c,c+d),a.X=d;if(0===a.X&&0===e)return a.S=b.slice(c,c+d),a.X=d;if(e+d<=a.X)return a.S.set(b.subarray(c,c+d),e),d}X.Ma(a,e+d);if(a.S.subarray&&b.subarray)a.S.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.S[e+f]=b[c+f];a.X=
Math.max(a.X,e+d);return d},la:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.X);if(0>b)throw new W(28);return b},Ja:function(a,b,c){X.Ma(a.node,b+c);a.node.X=Math.max(a.node.X,b+c)},Ra:function(a,b,c,d,e,f){if(0!==b)throw new W(28);if(32768!==(a.node.mode&61440))throw new W(43);a=a.node.S;if(f&2||a.buffer!==Ca){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;w();c=void 0;if(!c)throw new W(48);D.set(a,c)}else d=!1,
c=a.byteOffset;return{V:c,Bb:d}},Ta:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new W(43);if(e&2)return 0;X.U.write(a,b,0,d,c,!1);return 0}}},ic=null,jc={},kc=[],lc=1,mc=null,nc=!0,W=null,gc={},Y=(a,b={})=>{a=Xb("/",a);if(!a)return{path:"",node:null};b=Object.assign({Pa:!0,Ha:0},b);if(8<b.Ha)throw new W(32);a=Sb(a.split("/").filter(k=>!!k),!1);for(var c=ic,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=hc(c,a[e]);d=Tb(d+"/"+a[e]);c.ya&&(!f||f&&b.Pa)&&(c=c.ya.root);
if(!f||b.Oa)for(f=0;40960===(c.mode&61440);)if(c=oc(d),d=Xb(Ub(d),c),c=Y(d,{Ha:b.Ha+1}).node,40<f++)throw new W(32);}return{path:d,node:c}},rc=a=>{for(var b;;){if(a===a.parent)return a=a.ha.Sa,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},sc=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%mc.length},hc=(a,b)=>{var c;if(c=(c=tc(a,"x"))?c:a.T.lookup?0:2)throw new W(c,a);for(c=mc[sc(a.id,b)];c;c=c.mb){var d=c.name;if(c.parent.id===a.id&&
d===b)return c}return a.T.lookup(a,b)},fc=(a,b,c,d)=>{a=new uc(a,b,c,d);b=sc(a.parent.id,a.name);a.mb=mc[b];return mc[b]=a},vc={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},wc=a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},tc=(a,b)=>{if(nc)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},xc=(a,b)=>{try{return hc(a,b),20}catch(c){}return tc(a,"wx")},yc=(a=0,b=4096)=>{for(;a<=b;a++)if(!kc[a])return a;
throw new W(33);},Ac=a=>{zc||(zc=function(){},zc.prototype={});a=Object.assign(new zc,a);var b=yc(void 0,void 0);a.fd=b;return kc[b]=a},ec={open:a=>{a.U=jc[a.node.rdev].U;a.U.open&&a.U.open(a)},la:()=>{throw new W(70);}},$b=(a,b)=>{jc[a]={U:b}},Bc=(a,b)=>{var c="/"===b,d=!b;if(c&&ic)throw new W(10);if(!c&&!d){var e=Y(b,{Pa:!1});b=e.path;e=e.node;if(e.ya)throw new W(10);if(16384!==(e.mode&61440))throw new W(54);}b={type:a,Fb:{},Sa:b,lb:[]};a=a.ha(b);a.ha=b;b.root=a;c?ic=a:e&&(e.ya=b,e.ha&&e.ha.lb.push(b))},
Z=(a,b,c)=>{var d=Y(a,{parent:!0}).node;a=Vb(a);if(!a||"."===a||".."===a)throw new W(28);var e=xc(d,a);if(e)throw new W(e);if(!d.T.xa)throw new W(63);return d.T.xa(d,a,b,c)},Cc=(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);Z(a,b|8192,c)},Dc=(a,b)=>{if(!Xb(a))throw new W(44);var c=Y(b,{parent:!0}).node;if(!c)throw new W(44);b=Vb(b);var d=xc(c,b);if(d)throw new W(d);if(!c.T.symlink)throw new W(63);c.T.symlink(c,b,a)},oc=a=>{a=Y(a).node;if(!a)throw new W(44);if(!a.T.readlink)throw new W(28);return Xb(rc(a.parent),
a.T.readlink(a))},Fc=(a,b)=>{if(""===a)throw new W(44);if("string"==typeof b){var c=vc[b];if("undefined"==typeof c)throw Error("Unknown file open mode: "+b);b=c}var d=b&64?("undefined"==typeof d?438:d)&4095|32768:0;if("object"==typeof a)var e=a;else{a=Tb(a);try{e=Y(a,{Oa:!(b&131072)}).node}catch(f){}}c=!1;if(b&64)if(e){if(b&128)throw new W(20);}else e=Z(a,d,0),c=!0;if(!e)throw new W(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new W(54);if(!c&&(d=e?40960===(e.mode&
61440)?32:16384===(e.mode&61440)&&("r"!==wc(b)||b&512)?31:tc(e,wc(b)):44))throw new W(d);if(b&512){d=e;d="string"==typeof d?Y(d,{Oa:!0}).node:d;if(!d.T.ga)throw new W(63);if(16384===(d.mode&61440))throw new W(31);if(32768!==(d.mode&61440))throw new W(28);if(c=tc(d,"w"))throw new W(c);d.T.ga(d,{size:0,timestamp:Date.now()})}b&=-131713;e=Ac({node:e,path:rc(e),flags:b,seekable:!0,position:0,U:e.U,Ab:[],error:!1});e.U.open&&e.U.open(e);!h.logReadFiles||b&1||(Ec||(Ec={}),a in Ec||(Ec[a]=1))},Gc=(a,b,c)=>
{if(null===a.fd)throw new W(8);if(!a.seekable||!a.U.la)throw new W(70);if(0!=c&&1!=c&&2!=c)throw new W(28);a.position=a.U.la(a,b,c);a.Ab=[]},Hc=()=>{W||(W=function(a,b){this.node=b;this.rb=function(c){this.ua=c};this.rb(a);this.message="FS error"},W.prototype=Error(),W.prototype.constructor=W,[44].forEach(a=>{gc[a]=new W(a);gc[a].stack="<generic error, no stack>"}))},Ic,Jc=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Lc=(a,b,c)=>{a=Tb("/dev/"+a);var d=Jc(!!b,!!c);Kc||(Kc=64);var e=Kc++<<8|0;
$b(e,{open:f=>{f.seekable=!1},close:()=>{c&&c.buffer&&c.buffer.length&&c(10)},read:(f,k,l,n)=>{for(var p=0,q=0;q<n;q++){try{var u=b()}catch(y){throw new W(29);}if(void 0===u&&0===p)throw new W(6);if(null===u||void 0===u)break;p++;k[l+q]=u}p&&(f.node.timestamp=Date.now());return p},write:(f,k,l,n)=>{for(var p=0;p<n;p++)try{c(k[l+p])}catch(q){throw new W(29);}n&&(f.node.timestamp=Date.now());return p}});Cc(a,d,e)},Kc,Mc={},zc,Ec;function Nc(a){a=kc[a];if(!a)throw new W(8);return a}
function Oc(a){return 0===a%4&&(0!==a%100||0===a%400)}function Pc(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Qc=[31,29,31,30,31,30,31,31,30,31,30,31],Rc=[31,28,31,30,31,30,31,31,30,31,30,31];function Sc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Oc(a.getFullYear())?Qc:Rc)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Tc(a,b,c,d){function e(g,r,v){for(g="number"==typeof g?g.toString():g||"";g.length<r;)g=v[0]+g;return g}function f(g,r){return e(g,r,"0")}function k(g,r){function v(P){return 0>P?-1:0<P?1:0}var z;0===(z=v(g.getFullYear()-r.getFullYear()))&&0===(z=v(g.getMonth()-r.getMonth()))&&(z=v(g.getDate()-r.getDate()));return z}function l(g){switch(g.getDay()){case 0:return new Date(g.getFullYear()-1,11,29);case 1:return g;case 2:return new Date(g.getFullYear(),0,3);case 3:return new Date(g.getFullYear(),
0,2);case 4:return new Date(g.getFullYear(),0,1);case 5:return new Date(g.getFullYear()-1,11,31);case 6:return new Date(g.getFullYear()-1,11,30)}}function n(g){g=Sc(new Date(g.$+1900,0,1),g.Ba);var r=new Date(g.getFullYear()+1,0,4),v=l(new Date(g.getFullYear(),0,4));r=l(r);return 0>=k(v,g)?0>=k(r,g)?g.getFullYear()+1:g.getFullYear():g.getFullYear()-1}var p=C[d+40>>2];d={yb:C[d>>2],xb:C[d+4>>2],za:C[d+8>>2],ra:C[d+12>>2],pa:C[d+16>>2],$:C[d+20>>2],Aa:C[d+24>>2],Ba:C[d+28>>2],Gb:C[d+32>>2],wb:C[d+36>>
2],zb:p?p?x(A,p,void 0):"":""};c=c?x(A,c,void 0):"";p={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in p)c=c.replace(new RegExp(q,"g"),p[q]);var u="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
y="January February March April May June July August September October November December".split(" ");p={"%a":function(g){return u[g.Aa].substring(0,3)},"%A":function(g){return u[g.Aa]},"%b":function(g){return y[g.pa].substring(0,3)},"%B":function(g){return y[g.pa]},"%C":function(g){return f((g.$+1900)/100|0,2)},"%d":function(g){return f(g.ra,2)},"%e":function(g){return e(g.ra,2," ")},"%g":function(g){return n(g).toString().substring(2)},"%G":function(g){return n(g)},"%H":function(g){return f(g.za,
2)},"%I":function(g){g=g.za;0==g?g=12:12<g&&(g-=12);return f(g,2)},"%j":function(g){return f(g.ra+Pc(Oc(g.$+1900)?Qc:Rc,g.pa-1),3)},"%m":function(g){return f(g.pa+1,2)},"%M":function(g){return f(g.xb,2)},"%n":function(){return"\n"},"%p":function(g){return 0<=g.za&&12>g.za?"AM":"PM"},"%S":function(g){return f(g.yb,2)},"%t":function(){return"\t"},"%u":function(g){return g.Aa||7},"%U":function(g){var r=new Date(g.$+1900,0,1),v=0===r.getDay()?r:Sc(r,7-r.getDay());g=new Date(g.$+1900,g.pa,g.ra);return 0>
k(v,g)?f(Math.ceil((31-v.getDate()+(Pc(Oc(g.getFullYear())?Qc:Rc,g.getMonth()-1)-31)+g.getDate())/7),2):0===k(v,r)?"01":"00"},"%V":function(g){var r=new Date(g.$+1901,0,4),v=l(new Date(g.$+1900,0,4));r=l(r);var z=Sc(new Date(g.$+1900,0,1),g.Ba);return 0>k(z,v)?"53":0>=k(r,z)?"01":f(Math.ceil((v.getFullYear()<g.$+1900?g.Ba+32-v.getDate():g.Ba+1-v.getDate())/7),2)},"%w":function(g){return g.Aa},"%W":function(g){var r=new Date(g.$,0,1),v=1===r.getDay()?r:Sc(r,0===r.getDay()?1:7-r.getDay()+1);g=new Date(g.$+
1900,g.pa,g.ra);return 0>k(v,g)?f(Math.ceil((31-v.getDate()+(Pc(Oc(g.getFullYear())?Qc:Rc,g.getMonth()-1)-31)+g.getDate())/7),2):0===k(v,r)?"01":"00"},"%y":function(g){return(g.$+1900).toString().substring(2)},"%Y":function(g){return g.$+1900},"%z":function(g){g=g.wb;var r=0<=g;g=Math.abs(g)/60;return(r?"+":"-")+String("0000"+(g/60*100+g%60)).slice(-4)},"%Z":function(g){return g.zb},"%%":function(){return"%"}};c=c.replace(/%%/g,"\x00\x00");for(q in p)c.includes(q)&&(c=c.replace(new RegExp(q,"g"),
p[q](d)));c=c.replace(/\0\0/g,"%");q=bc(c,!1);if(q.length>b)return 0;D.set(q,a);return q.length-1}cb=h.InternalError=bb("InternalError");for(var Uc=Array(256),Vc=0;256>Vc;++Vc)Uc[Vc]=String.fromCharCode(Vc);fb=Uc;O=h.BindingError=bb("BindingError");R.prototype.isAliasOf=function(a){if(!(this instanceof R&&a instanceof R))return!1;var b=this.R.Y.W,c=this.R.V,d=a.R.Y.W;for(a=a.R.V;b.ba;)c=b.sa(c),b=b.ba;for(;d.ba;)a=d.sa(a),d=d.ba;return b===d&&c===a};
R.prototype.clone=function(){this.R.V||gb(this);if(this.R.qa)return this.R.count.value+=1,this;var a=sb,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.R;a=a(c.call(b,d,{R:{value:{count:e.count,ma:e.ma,qa:e.qa,V:e.V,Y:e.Y,Z:e.Z,aa:e.aa}}}));a.R.count.value+=1;a.R.ma=!1;return a};R.prototype["delete"]=function(){this.R.V||gb(this);this.R.ma&&!this.R.qa&&Q("Object already scheduled for deletion");ib(this);jb(this.R);this.R.qa||(this.R.Z=void 0,this.R.V=void 0)};R.prototype.isDeleted=function(){return!this.R.V};
R.prototype.deleteLater=function(){this.R.V||gb(this);this.R.ma&&!this.R.qa&&Q("Object already scheduled for deletion");mb.push(this);1===mb.length&&ob&&ob(nb);this.R.ma=!0;return this};h.getInheritedInstanceCount=function(){return Object.keys(pb).length};h.getLiveInheritedInstances=function(){var a=[],b;for(b in pb)pb.hasOwnProperty(b)&&a.push(pb[b]);return a};h.flushPendingDeletes=nb;h.setDelayFunction=function(a){ob=a;mb.length&&ob&&ob(nb)};S.prototype.gb=function(a){this.Ua&&(a=this.Ua(a));return a};
S.prototype.La=function(a){this.ia&&this.ia(a)};S.prototype.argPackAdvance=8;S.prototype.readValueFromPointer=Ya;S.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
S.prototype.fromWireType=function(a){function b(){return this.wa?rb(this.W.na,{Y:this.nb,V:c,aa:this,Z:a}):rb(this.W.na,{Y:this,V:a})}var c=this.gb(a);if(!c)return this.La(a),null;var d=qb(this.W,c);if(void 0!==d){if(0===d.R.count.value)return d.R.V=c,d.R.Z=a,d.clone();d=d.clone();this.La(a);return d}d=this.W.fb(c);d=lb[d];if(!d)return b.call(this);d=this.va?d.bb:d.pointerType;var e=kb(c,this.W,d.W);return null===e?b.call(this):this.wa?rb(d.W.na,{Y:d,V:e,aa:this,Z:a}):rb(d.W.na,{Y:d,V:e})};
Eb=h.UnboundTypeError=bb("UnboundTypeError");h.count_emval_handles=function(){for(var a=0,b=5;b<V.length;++b)void 0!==V[b]&&++a;return a};h.get_first_emval=function(){for(var a=5;a<V.length;++a)if(void 0!==V[a])return V[a];return null};function uc(a,b,c,d){a||(a=this);this.parent=a;this.ha=a.ha;this.ya=null;this.id=lc++;this.name=b;this.mode=c;this.T={};this.U={};this.rdev=d}
Object.defineProperties(uc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Hc();mc=Array(4096);Bc(X,"/");Z("/tmp",16895,0);Z("/home",16895,0);Z("/home/web_user",16895,0);
(()=>{Z("/dev",16895,0);$b(259,{read:()=>0,write:(b,c,d,e)=>e});Cc("/dev/null",259);Zb(1280,cc);Zb(1536,dc);Cc("/dev/tty",1280);Cc("/dev/tty1",1536);var a=Wb();Lc("random",a);Lc("urandom",a);Z("/dev/shm",16895,0);Z("/dev/shm/tmp",16895,0)})();
(()=>{Z("/proc",16895,0);var a=Z("/proc/self",16895,0);Z("/proc/self/fd",16895,0);Bc({ha:()=>{var b=fc(a,"fd",16895,73);b.T={lookup:(c,d)=>{var e=kc[+d];if(!e)throw new W(8);c={parent:null,ha:{Sa:"fake"},T:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();function bc(a,b){var c=Array(ta(a)+1);a=sa(a,c,0,c.length);b&&(c.length=a);return c}
var Xc={d:function(a){return Wc(a+16)+16},c:function(a,b,c){(new Ua(a)).Va(b,c);Va++;throw a;},z:function(a){var b=Wa[a];delete Wa[a];var c=b.Ga,d=b.ia,e=b.Na,f=e.map(function(k){return k.jb}).concat(e.map(function(k){return k.tb}));K([a],f,function(k){var l={};e.forEach(function(n,p){var q=k[p],u=n.hb,y=n.ib,g=k[p+e.length],r=n.sb,v=n.ub;l[n.eb]={read:function(z){return q.fromWireType(u(y,z))},write:function(z,P){var M=[];r(v,z,g.toWireType(M,P));Xa(M)}}});return[{name:b.name,fromWireType:function(n){var p=
{},q;for(q in l)p[q]=l[q].read(n);d(n);return p},toWireType:function(n,p){for(var q in l)if(!(q in p))throw new TypeError('Missing field:  "'+q+'"');var u=c();for(q in l)l[q].write(u,p[q]);null!==n&&n.push(d,u);return u},argPackAdvance:8,readValueFromPointer:Ya,da:d}]})},r:function(){},C:function(a,b,c,d,e){var f=eb(c);b=N(b);L(a,{name:b,fromWireType:function(k){return!!k},toWireType:function(k,l){return l?d:e},argPackAdvance:8,readValueFromPointer:function(k){if(1===c)var l=D;else if(2===c)l=B;else if(4===
c)l=C;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(l[k>>f])},da:null})},i:function(a,b,c,d,e,f,k,l,n,p,q,u,y){q=N(q);f=T(e,f);l&&(l=T(k,l));p&&(p=T(n,p));y=T(u,y);var g=$a(q);ub(g,function(){Hb("Cannot construct "+q+" due to unbound types",[d])});K([a,b,c],d?[d]:[],function(r){r=r[0];if(d){var v=r.W;var z=v.na}else z=R.prototype;r=ab(g,function(){if(Object.getPrototypeOf(this)!==P)throw new O("Use 'new' to construct "+q);if(void 0===M.ka)throw new O(q+" has no accessible constructor");
var pc=M.ka[arguments.length];if(void 0===pc)throw new O("Tried to invoke ctor of "+q+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(M.ka).toString()+") parameters instead!");return pc.apply(this,arguments)});var P=Object.create(z,{constructor:{value:r}});r.prototype=P;var M=new vb(q,r,P,y,v,f,l,p);v=new S(q,M,!0,!1);z=new S(q+"*",M,!1,!1);var qc=new S(q+" const*",M,!1,!0);lb[a]={pointerType:z,bb:qc};Cb(g,r);return[v,z,qc]})},h:function(a,b,c,d,e,f){0<b||w(void 0);
var k=Ib(b,c);e=T(d,e);K([],[a],function(l){l=l[0];var n="constructor "+l.name;void 0===l.W.ka&&(l.W.ka=[]);if(void 0!==l.W.ka[b-1])throw new O("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+l.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");l.W.ka[b-1]=()=>{Hb("Cannot construct "+l.name+" due to unbound types",k)};K([],k,function(p){p.splice(1,0,null);l.W.ka[b-1]=Kb(n,p,null,e,f);return[]});
return[]})},a:function(a,b,c,d,e,f,k,l){var n=Ib(c,d);b=N(b);f=T(e,f);K([],[a],function(p){function q(){Hb("Cannot call "+u+" due to unbound types",n)}p=p[0];var u=p.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);l&&p.W.ob.push(b);var y=p.W.na,g=y[b];void 0===g||void 0===g.fa&&g.className!==p.name&&g.ta===c-2?(q.ta=c-2,q.className=p.name,y[b]=q):(tb(y,b,u),y[b].fa[c-2]=q);K([],n,function(r){r=Kb(u,r,p,f,k);void 0===y[b].fa?(r.ta=c-2,y[b]=r):y[b].fa[c-2]=r;return[]});return[]})},B:function(a,
b){b=N(b);L(a,{name:b,fromWireType:function(c){c||Q("Cannot use deleted val. handle = "+c);var d=V[c].value;Mb(c);return d},toWireType:function(c,d){return Ab(d)},argPackAdvance:8,readValueFromPointer:Ya,da:null})},o:function(a,b,c){c=eb(c);b=N(b);L(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){return e},argPackAdvance:8,readValueFromPointer:Nb(b,c),da:null})},f:function(a,b,c,d,e){b=N(b);-1===e&&(e=4294967295);e=eb(c);var f=l=>l;if(0===d){var k=32-8*c;f=l=>l<<k>>>k}c=b.includes("unsigned")?
function(l,n){return n>>>0}:function(l,n){return n};L(a,{name:b,fromWireType:f,toWireType:c,argPackAdvance:8,readValueFromPointer:Ob(b,e,0!==d),da:null})},b:function(a,b,c){function d(f){f>>=2;var k=E;return new e(Ca,k[f+1],k[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=N(c);L(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{kb:!0})},n:function(a,b){b=N(b);var c="std::string"===b;L(a,{name:b,fromWireType:function(d){var e=
E[d>>2];if(c)for(var f=d+4,k=0;k<=e;++k){var l=d+4+k;if(k==e||0==A[l]){f=f?x(A,f,l-f):"";if(void 0===n)var n=f;else n+=String.fromCharCode(0),n+=f;f=l+1}}else{n=Array(e);for(k=0;k<e;++k)n[k]=String.fromCharCode(A[d+4+k]);n=n.join("")}U(d);return n},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"==typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||Q("Cannot pass non-string to std::string");var k=(c&&f?()=>ta(e):()=>e.length)(),
l=Wc(4+k+1);E[l>>2]=k;if(c&&f)sa(e,A,l+4,k+1);else if(f)for(f=0;f<k;++f){var n=e.charCodeAt(f);255<n&&(U(l),Q("String has UTF-16 code units that do not fit in 8 bits"));A[l+4+f]=n}else for(f=0;f<k;++f)A[l+4+f]=e[f];null!==d&&d.push(U,l);return l},argPackAdvance:8,readValueFromPointer:Ya,da:function(d){U(d)}})},k:function(a,b,c){c=N(c);if(2===b){var d=va;var e=xa;var f=ya;var k=()=>wa;var l=1}else 4===b&&(d=za,e=Aa,f=Ba,k=()=>E,l=2);L(a,{name:c,fromWireType:function(n){for(var p=E[n>>2],q=k(),u,y=
n+4,g=0;g<=p;++g){var r=n+4+g*b;if(g==p||0==q[r>>l])y=d(y,r-y),void 0===u?u=y:(u+=String.fromCharCode(0),u+=y),y=r+b}U(n);return u},toWireType:function(n,p){"string"!=typeof p&&Q("Cannot pass non-string to C++ string type "+c);var q=f(p),u=Wc(4+q+b);E[u>>2]=q>>l;e(p,u+4,q+b);null!==n&&n.push(U,u);return u},argPackAdvance:8,readValueFromPointer:Ya,da:function(n){U(n)}})},E:function(a,b,c,d,e,f){Wa[a]={name:N(b),Ga:T(c,d),ia:T(e,f),Na:[]}},e:function(a,b,c,d,e,f,k,l,n,p){Wa[a].Na.push({eb:N(b),jb:c,
hb:T(d,e),ib:f,tb:k,sb:T(l,n),ub:p})},D:function(a,b){b=N(b);L(a,{Eb:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},p:Mb,l:function(a){4<a&&(V[a].Ia+=1)},g:function(a,b){var c=J[a];void 0===c&&Q("_emval_take_value has unknown type "+Fb(a));a=c;a=a.readValueFromPointer(b);return Ab(a)},j:function(){w("")},A:function(a,b,c){A.copyWithin(a,b,b+c)},y:function(){w("OOM")},u:function(a,b){var c=0;Qb().forEach(function(d,e){var f=b+c;e=C[a+4*e>>2]=f;for(f=0;f<d.length;++f)D[e++>>
0]=d.charCodeAt(f);D[e>>0]=0;c+=d.length+1});return 0},v:function(a,b){var c=Qb();C[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});C[b>>2]=d;return 0},w:function(a){try{var b=Nc(a);if(null===b.fd)throw new W(8);b.Da&&(b.Da=null);try{b.U.close&&b.U.close(b)}catch(c){throw c;}finally{kc[b.fd]=null}b.fd=null;return 0}catch(c){if("undefined"==typeof Mc||!(c instanceof W))throw c;return c.ua}},x:function(a,b,c,d){try{a:{for(var e=Nc(a),f=a=0;f<c;f++){var k=C[b+(8*f+4)>>2],l=e,n=C[b+8*f>>
2],p=k,q=void 0,u=D;if(0>p||0>q)throw new W(28);if(null===l.fd)throw new W(8);if(1===(l.flags&2097155))throw new W(8);if(16384===(l.node.mode&61440))throw new W(31);if(!l.U.read)throw new W(28);var y="undefined"!=typeof q;if(!y)q=l.position;else if(!l.seekable)throw new W(70);var g=l.U.read(l,u,n,p,q);y||(l.position+=g);var r=g;if(0>r){var v=-1;break a}a+=r;if(r<k)break}v=a}C[d>>2]=v;return 0}catch(z){if("undefined"==typeof Mc||!(z instanceof W))throw z;return z.ua}},q:function(a,b,c,d,e){try{var f=
Nc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Gc(f,a,d);Qa=[f.position>>>0,(H=f.position,1<=+Math.abs(H)?0<H?(Math.min(+Math.floor(H/4294967296),4294967295)|0)>>>0:~~+Math.ceil((H-+(~~H>>>0))/4294967296)>>>0:0)];C[e>>2]=Qa[0];C[e+4>>2]=Qa[1];f.Da&&0===a&&0===d&&(f.Da=null);return 0}catch(k){if("undefined"==typeof Mc||!(k instanceof W))throw k;return k.ua}},m:function(a,b,c,d){try{a:{for(var e=Nc(a),f=a=0;f<c;f++){var k=e,l=C[b+8*f>>2],n=C[b+(8*f+4)>>2],p=void 0,
q=D;if(0>n||0>p)throw new W(28);if(null===k.fd)throw new W(8);if(0===(k.flags&2097155))throw new W(8);if(16384===(k.node.mode&61440))throw new W(31);if(!k.U.write)throw new W(28);k.seekable&&k.flags&1024&&Gc(k,0,2);var u="undefined"!=typeof p;if(!u)p=k.position;else if(!k.seekable)throw new W(70);var y=k.U.write(k,q,l,n,p,void 0);u||(k.position+=y);var g=y;if(0>g){var r=-1;break a}a+=g}r=a}C[d>>2]=r;return 0}catch(v){if("undefined"==typeof Mc||!(v instanceof W))throw v;return v.ua}},s:function(){},
t:function(a,b,c,d){return Tc(a,b,c,d)}};
(function(){function a(e){h.asm=e.exports;pa=h.asm.F;Ca=e=pa.buffer;h.HEAP8=D=new Int8Array(e);h.HEAP16=B=new Int16Array(e);h.HEAP32=C=new Int32Array(e);h.HEAPU8=A=new Uint8Array(e);h.HEAPU16=wa=new Uint16Array(e);h.HEAPU32=E=new Uint32Array(e);h.HEAPF32=Da=new Float32Array(e);h.HEAPF64=Ea=new Float64Array(e);Fa=h.asm.I;Ha.unshift(h.asm.G);F--;h.monitorRunDependencies&&h.monitorRunDependencies(F);0==F&&(null!==Ka&&(clearInterval(Ka),Ka=null),La&&(e=La,La=null,e()))}function b(e){a(e.instance)}function c(e){return Pa().then(function(f){return WebAssembly.instantiate(f,
d)}).then(function(f){return f}).then(e,function(f){t("failed to asynchronously prepare wasm: "+f);w(f)})}var d={a:Xc};F++;h.monitorRunDependencies&&h.monitorRunDependencies(F);if(h.instantiateWasm)try{return h.instantiateWasm(d,a)}catch(e){return t("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return oa||"function"!=typeof WebAssembly.instantiateStreaming||Ma()||G.startsWith("file://")||"function"!=typeof fetch?c(b):fetch(G,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,
d).then(b,function(f){t("wasm streaming compile failed: "+f);t("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();h.___wasm_call_ctors=function(){return(h.___wasm_call_ctors=h.asm.G).apply(null,arguments)};var Wc=h._malloc=function(){return(Wc=h._malloc=h.asm.H).apply(null,arguments)},Gb=h.___getTypeName=function(){return(Gb=h.___getTypeName=h.asm.J).apply(null,arguments)};
h.___embind_register_native_and_builtin_types=function(){return(h.___embind_register_native_and_builtin_types=h.asm.K).apply(null,arguments)};var U=h._free=function(){return(U=h._free=h.asm.L).apply(null,arguments)};h.dynCall_viijii=function(){return(h.dynCall_viijii=h.asm.M).apply(null,arguments)};h.dynCall_jiji=function(){return(h.dynCall_jiji=h.asm.N).apply(null,arguments)};h.dynCall_iiiiij=function(){return(h.dynCall_iiiiij=h.asm.O).apply(null,arguments)};
h.dynCall_iiiiijj=function(){return(h.dynCall_iiiiijj=h.asm.P).apply(null,arguments)};h.dynCall_iiiiiijj=function(){return(h.dynCall_iiiiiijj=h.asm.Q).apply(null,arguments)};var Yc;La=function Zc(){Yc||$c();Yc||(La=Zc)};
function $c(){function a(){if(!Yc&&(Yc=!0,h.calledRun=!0,!qa)){h.noFSInit||Ic||(Ic=!0,Hc(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?Lc("stdin",h.stdin):Dc("/dev/tty","/dev/stdin"),h.stdout?Lc("stdout",null,h.stdout):Dc("/dev/tty","/dev/stdout"),h.stderr?Lc("stderr",null,h.stderr):Dc("/dev/tty1","/dev/stderr"),Fc("/dev/stdin",0),Fc("/dev/stdout",1),Fc("/dev/stderr",1));nc=!1;Ra(Ha);aa(h);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(h.postRun)for("function"==typeof h.postRun&&
(h.postRun=[h.postRun]);h.postRun.length;){var b=h.postRun.shift();Ia.unshift(b)}Ra(Ia)}}if(!(0<F)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ja();Ra(Ga);0<F||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);a()},1)):a())}}h.run=$c;if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();$c();


  return Module.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Module;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return Module; });
else if (typeof exports === 'object')
  exports["Module"] = Module;
